from pybricks.parameters import Port, Color

# --- HARDWARE CONFIG (Puertos) ---
PORT_MOTOR_IZQ = Port.B
PORT_MOTOR_DER = Port.E
PORT_GARRA_TRASERA = Port.F
PORT_GARRA_DELANTERA = Port.C
PORT_PINZA = Port.A
PORT_SENSOR_FRENTE = Port.D

# --- MECANISMOS CONFIG (Grados máximos calibrados) ---
RANGO_MAXIMO_GARRA_TRASERA = -180
RANGO_MAXIMO_GARRA_DELANTERA = 672
RANGO_MAXIMO_PINZA = 798

# --- CHASIS CONFIG (Medidas físicas) ---
DIAMETRO_RUEDA = 56
SEPARACION_RUEDAS = 160

# --- NAVEGACIÓN CONFIG (Velocidades) ---
VELOCIDAD_BASE = 950
STRAIGHT_SPEED = 700
STRAIGHT_ACCEL = 700
TURN_RATE = 500

# --- REGLAS DEL JUEGO ---
MOSAICOS = {
    Color.GREEN: {Color.GREEN: 1, Color.YELLOW: 2}, 
    Color.BLUE: 3, 
    Color.YELLOW: 4, 
    Color.WHITE: 5
}

# --- OPCIONES DE SISTEMA ---
USAR_MOTOR_SIMULADO = False
SONIDO_ACTIVO = False
BATERIA_MINIMA = 8150